create table if not exists public.home_hero (
  id bigint primary key,
  main_title text not null,
  subtitle text not null,
  description text not null,
  primary_button_label text not null,
  primary_button_href text not null,
  secondary_button_label text not null,
  secondary_button_href text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_stats (
  position integer primary key,
  title text not null,
  value integer not null,
  suffix text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_mission (
  id bigint primary key,
  title text not null,
  description text not null,
  image_url text not null default '',
  image_path text not null default '',
  card1_title text not null,
  card1_description text not null,
  card2_title text not null,
  card2_description text not null,
  card3_title text not null,
  card3_description text not null,
  card4_title text not null,
  card4_description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_featured_stock (
  id bigint primary key,
  eyebrow text not null,
  title text not null,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_company_values (
  id bigint primary key,
  eyebrow text not null,
  title text not null,
  description text not null,
  benefit1 text not null,
  benefit2 text not null,
  benefit3 text not null,
  benefit4 text not null,
  benefit5 text not null,
  button_label text not null,
  button_href text not null,
  image_url text not null default '',
  image_path text not null default '',
  highlight_title text not null,
  highlight_description text not null,
  highlight_button_label text not null,
  highlight_button_href text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_trusted_by (
  id bigint primary key,
  title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_steps (
  id bigint primary key,
  title text not null,
  step1_title text not null,
  step1_description text not null,
  step1_image_url text not null default '',
  step1_image_path text not null default '',
  step2_title text not null,
  step2_description text not null,
  step2_image_url text not null default '',
  step2_image_path text not null default '',
  step3_title text not null,
  step3_description text not null,
  step3_image_url text not null default '',
  step3_image_path text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_testimonials_section (
  id bigint primary key,
  title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_testimonials (
  position integer primary key,
  name text not null,
  role text not null,
  quote text not null,
  rating integer not null default 5,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_news (
  id bigint primary key,
  title text not null,
  button_label text not null,
  button_href text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  username text not null unique,
  created_at timestamptz not null default now()
);
