import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LenisProvider } from "@/components/lenis-provider";
import { AdminFab } from "@/components/admin/admin-fab";
import { Toaster } from "@/components/ui/sonner";

const gilroyLight = localFont({
  src: "../public/fonts/Gilroy-Light.woff2",
  weight: "300",
  style: "normal",
  variable: "--font-gilroy-light",
  display: "swap",
});

const gilroyExtraBold = localFont({
  src: "../public/fonts/Gilroy-ExtraBold.woff2",
  weight: "800",
  style: "normal",
  variable: "--font-gilroy-extrabold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroyLight.variable} ${gilroyExtraBold.variable} antialiased`}
      >
        <LenisProvider>
          {children}
          <AdminFab />
          <Toaster position="top-right" />
        </LenisProvider>
      </body>
    </html>
  );
}
